#Swift Mailer
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:      { type: memory }
    port:      '%mailer_port'
    encryption: '%mailer_encryption%'
    auth_mode: 'login'