<?php

namespace kapla\gallery\Repository;

/**
 * ImgGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
